{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.1.jar",
          "url": "xtechads-gradle-plugin-1.5.1.jar",
          "size": 14906,
          "sha512": "2d5c70a9044bc896f9d3e5262d75cae8c47d7607517cfa4512e6227eb1eb27f67e02fae08e6cd2c3e72c03019d086fcfeb1c3e35bb658ef09af9471217a31d42",
          "sha256": "6efa1701fd22077d5ca520bef8e3a9e2858965a55b8ae3f7de0af9f987a9cfbc",
          "sha1": "af80a9f005638b6d2385a77f5bb3178cfe86c1a6",
          "md5": "e3de3f567465ff1dcd079a2cf50bbc2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.1.jar",
          "url": "xtechads-gradle-plugin-1.5.1.jar",
          "size": 14906,
          "sha512": "2d5c70a9044bc896f9d3e5262d75cae8c47d7607517cfa4512e6227eb1eb27f67e02fae08e6cd2c3e72c03019d086fcfeb1c3e35bb658ef09af9471217a31d42",
          "sha256": "6efa1701fd22077d5ca520bef8e3a9e2858965a55b8ae3f7de0af9f987a9cfbc",
          "sha1": "af80a9f005638b6d2385a77f5bb3178cfe86c1a6",
          "md5": "e3de3f567465ff1dcd079a2cf50bbc2e"
        }
      ]
    }
  ]
}
