{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.1.jar",
          "url": "xtechads-gradle-plugin-1.3.1.jar",
          "size": 14906,
          "sha512": "418b175f6e8c0d39076111804290e534b981072c52d5500c93d2e01f666c9bf37efebc620b6590fc0bee817d4ef2a29786575710e286a505c302d80cefbd4109",
          "sha256": "08a9499c4bfbbfe21288f5fb4d53a9d3f18e2ddc2aa167cf6c7e11b435d63b59",
          "sha1": "f5ebd2853164a0bdcb296f03a1dc778fbdc42b5c",
          "md5": "d51de9459d6915ef5ff2e04a5f01a458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.1.jar",
          "url": "xtechads-gradle-plugin-1.3.1.jar",
          "size": 14906,
          "sha512": "418b175f6e8c0d39076111804290e534b981072c52d5500c93d2e01f666c9bf37efebc620b6590fc0bee817d4ef2a29786575710e286a505c302d80cefbd4109",
          "sha256": "08a9499c4bfbbfe21288f5fb4d53a9d3f18e2ddc2aa167cf6c7e11b435d63b59",
          "sha1": "f5ebd2853164a0bdcb296f03a1dc778fbdc42b5c",
          "md5": "d51de9459d6915ef5ff2e04a5f01a458"
        }
      ]
    }
  ]
}
