{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.8.1.jar",
          "url": "xtechads-gradle-plugin-1.8.1.jar",
          "size": 14906,
          "sha512": "0751a6797026006a59f61e8177ef7378e23912e5cbb4903eb6c8ec6ae16b755a166abb80a6ee1df4660287007908751689dd88fa9467b9c1f5402684aa55177d",
          "sha256": "4e11748e8ac2781998fd1771037f0518bc77c58b7905ed5c95e8bd641ce8d564",
          "sha1": "c7b1f64b41d36d28f1266f6aea2d79e5603a3e6f",
          "md5": "a1609512698f77c3f375f6e645539e37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.8.1.jar",
          "url": "xtechads-gradle-plugin-1.8.1.jar",
          "size": 14906,
          "sha512": "0751a6797026006a59f61e8177ef7378e23912e5cbb4903eb6c8ec6ae16b755a166abb80a6ee1df4660287007908751689dd88fa9467b9c1f5402684aa55177d",
          "sha256": "4e11748e8ac2781998fd1771037f0518bc77c58b7905ed5c95e8bd641ce8d564",
          "sha1": "c7b1f64b41d36d28f1266f6aea2d79e5603a3e6f",
          "md5": "a1609512698f77c3f375f6e645539e37"
        }
      ]
    }
  ]
}
