{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.8.jar",
          "url": "xtechads-gradle-plugin-1.3.8.jar",
          "size": 14906,
          "sha512": "b5fe0be7f8f22b84410c56eae63cec226c76fd3ea9eca6bc6a7517f313fb5bcc8fb497ff780f4d63391a165ed82caa6e336ce53986f95a3ef57707fbd20bc63d",
          "sha256": "67d5d9e8083914ab7a359aff814f0059200425085e2230275b9115848013d4b5",
          "sha1": "3235879ee07aae01cc028fca521b2d6e66f0a227",
          "md5": "021cfa9bf9701c8a63c2a034d631cc4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.8.jar",
          "url": "xtechads-gradle-plugin-1.3.8.jar",
          "size": 14906,
          "sha512": "b5fe0be7f8f22b84410c56eae63cec226c76fd3ea9eca6bc6a7517f313fb5bcc8fb497ff780f4d63391a165ed82caa6e336ce53986f95a3ef57707fbd20bc63d",
          "sha256": "67d5d9e8083914ab7a359aff814f0059200425085e2230275b9115848013d4b5",
          "sha1": "3235879ee07aae01cc028fca521b2d6e66f0a227",
          "md5": "021cfa9bf9701c8a63c2a034d631cc4b"
        }
      ]
    }
  ]
}
