{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "ProductionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.adjust.sdk",
          "module": "adjust-android",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.4.8.aar",
          "url": "xtechads-1.4.8.aar",
          "size": 1668841,
          "sha512": "e02a932e65e0f40c774ab950b27ed0ad13dec7731b3928afe7bef9e75ef92f2073e7bfc00f050f15b46c5a85f7d0842b9ee39a0c7bf181949a8cdfdbb42200bc",
          "sha256": "b9e31909ecf7e78c19f4e4bb8ae34a04f818f89493db5f6886dca78c0ba719fa",
          "sha1": "af1b619296eaa88941c293ea011c048b34c169e7",
          "md5": "83055da021b68adbd3aa6298b4c23b20"
        }
      ]
    },
    {
      "name": "ProductionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.valentinilk.shimmer",
          "module": "compose-shimmer",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.adjust.signature",
          "module": "adjust-android-signature",
          "version": {
            "requires": "3.67.0"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "samsung-referrer",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "xiaomi-referrer",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "huawei-referrer",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.adjust.sdk",
          "module": "adjust-android",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.4.8.aar",
          "url": "xtechads-1.4.8.aar",
          "size": 1668841,
          "sha512": "e02a932e65e0f40c774ab950b27ed0ad13dec7731b3928afe7bef9e75ef92f2073e7bfc00f050f15b46c5a85f7d0842b9ee39a0c7bf181949a8cdfdbb42200bc",
          "sha256": "b9e31909ecf7e78c19f4e4bb8ae34a04f818f89493db5f6886dca78c0ba719fa",
          "sha1": "af1b619296eaa88941c293ea011c048b34c169e7",
          "md5": "83055da021b68adbd3aa6298b4c23b20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechads-1.4.8-sources.jar",
          "url": "xtechads-1.4.8-sources.jar",
          "size": 3644,
          "sha512": "2d586da98e24345aff313186bfd45e1b818fc342297c5b79614f8a7e0966eb3e5f65bd55f4e5b5cc12817e19246002f7414fedd50b04e9e4ca3ca9befab22377",
          "sha256": "74c450e4ccc085eae2e7291ea07e7c392840441caef905fc435e49992d047fc1",
          "sha1": "a897d8e8210a3b2045621e6fd9508744139ac6fd",
          "md5": "770c5ab866a34159f2ad3cea4809db0f"
        }
      ]
    }
  ]
}
