{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechcore",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechcore-1.0.0.aar",
          "url": "xtechcore-1.0.0.aar",
          "size": 22732,
          "sha512": "72f578c2c21dfcdd6d443c0fd6033f9ae7c5f170649ac271ae7052dda4550656a04353ef12def3f32677446255f9984261ad299e922b8ec4fafb2e107263a8a9",
          "sha256": "ef77df8678440fe2e628a49942cc13ca5c895ddec425c19ffac9a026eb5172ad",
          "sha1": "0c3feec0d07af61a6342c37ba8bddc3415d0556d",
          "md5": "1e0b18ca441f34e8a9371a58de817770"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechcore-1.0.0.aar",
          "url": "xtechcore-1.0.0.aar",
          "size": 22732,
          "sha512": "72f578c2c21dfcdd6d443c0fd6033f9ae7c5f170649ac271ae7052dda4550656a04353ef12def3f32677446255f9984261ad299e922b8ec4fafb2e107263a8a9",
          "sha256": "ef77df8678440fe2e628a49942cc13ca5c895ddec425c19ffac9a026eb5172ad",
          "sha1": "0c3feec0d07af61a6342c37ba8bddc3415d0556d",
          "md5": "1e0b18ca441f34e8a9371a58de817770"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechcore-1.0.0-sources.jar",
          "url": "xtechcore-1.0.0-sources.jar",
          "size": 6364,
          "sha512": "ffd8d55bb15e07ca41b5feb1fc8a92b2a8ebf1a3507927b7551d4163fa3ba0ece4cef979d05e7ed6ab710d13034897ffd470a0f25ac009bc4b28f52887f422f9",
          "sha256": "9a1dc28e7e849f2dc27015d03a3a43b881ab30b6b6b5e302a0d7be262338baea",
          "sha1": "d2f65f50d9393848f7881bc3094f7057d625b295",
          "md5": "ea01f0efd77689e38ebce735c43ca0a2"
        }
      ]
    }
  ]
}
