{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechcore",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechcore-1.0.0.aar",
          "url": "xtechcore-1.0.0.aar",
          "size": 22732,
          "sha512": "72f578c2c21dfcdd6d443c0fd6033f9ae7c5f170649ac271ae7052dda4550656a04353ef12def3f32677446255f9984261ad299e922b8ec4fafb2e107263a8a9",
          "sha256": "ef77df8678440fe2e628a49942cc13ca5c895ddec425c19ffac9a026eb5172ad",
          "sha1": "0c3feec0d07af61a6342c37ba8bddc3415d0556d",
          "md5": "1e0b18ca441f34e8a9371a58de817770"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechcore-1.0.0.aar",
          "url": "xtechcore-1.0.0.aar",
          "size": 22732,
          "sha512": "72f578c2c21dfcdd6d443c0fd6033f9ae7c5f170649ac271ae7052dda4550656a04353ef12def3f32677446255f9984261ad299e922b8ec4fafb2e107263a8a9",
          "sha256": "ef77df8678440fe2e628a49942cc13ca5c895ddec425c19ffac9a026eb5172ad",
          "sha1": "0c3feec0d07af61a6342c37ba8bddc3415d0556d",
          "md5": "1e0b18ca441f34e8a9371a58de817770"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechcore-1.0.0-sources.jar",
          "url": "xtechcore-1.0.0-sources.jar",
          "size": 6364,
          "sha512": "063317fa0ff55c28b6c3e8c40cebb20ad6d047884c999959883345047ea3b7b4ce09890d04f442467fb352fece7827b4657edc4f206dd9f8265560db06bdc54f",
          "sha256": "713c4f1d7b9dbc22969a9b5636e9d4a553780ee49cad7aaf1641a6b0e9811f1b",
          "sha1": "be5f9a2171ee879a1042ca178cc1b95f84a1c336",
          "md5": "bf781d10bc62e61e3ff43111f32cc793"
        }
      ]
    }
  ]
}
