{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechcore",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechcore-1.0.0.aar",
          "url": "xtechcore-1.0.0.aar",
          "size": 22732,
          "sha512": "72f578c2c21dfcdd6d443c0fd6033f9ae7c5f170649ac271ae7052dda4550656a04353ef12def3f32677446255f9984261ad299e922b8ec4fafb2e107263a8a9",
          "sha256": "ef77df8678440fe2e628a49942cc13ca5c895ddec425c19ffac9a026eb5172ad",
          "sha1": "0c3feec0d07af61a6342c37ba8bddc3415d0556d",
          "md5": "1e0b18ca441f34e8a9371a58de817770"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechcore-1.0.0.aar",
          "url": "xtechcore-1.0.0.aar",
          "size": 22732,
          "sha512": "72f578c2c21dfcdd6d443c0fd6033f9ae7c5f170649ac271ae7052dda4550656a04353ef12def3f32677446255f9984261ad299e922b8ec4fafb2e107263a8a9",
          "sha256": "ef77df8678440fe2e628a49942cc13ca5c895ddec425c19ffac9a026eb5172ad",
          "sha1": "0c3feec0d07af61a6342c37ba8bddc3415d0556d",
          "md5": "1e0b18ca441f34e8a9371a58de817770"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechcore-1.0.0-sources.jar",
          "url": "xtechcore-1.0.0-sources.jar",
          "size": 6364,
          "sha512": "e1ba3dcf48f4ba1f49200e945af62bda27047c92483a51c9eabcfdfb293eef0cc81c373b635b70d4c52208fac404ac94581ee2a8e95c6a93056a89076c45f56b",
          "sha256": "ea391521290678481d0c7700abe40d5c9c01f5d0c8fd56bed0dfd1fa37a0434c",
          "sha1": "d26bab850d4a26da9546133dea5fc43f36ebf896",
          "md5": "cebf67dc539111075b20f3895a2b9446"
        }
      ]
    }
  ]
}
