{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads",
    "version": "1.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "ProductionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.xtech.sdk",
          "module": "xtechcore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.18.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.7.7.aar",
          "url": "xtechads-1.7.7.aar",
          "size": 1686890,
          "sha512": "f8a8d951923a51be0626874550abd3a7de4d79ed16762141b65418b97ee486dd07cf0910e4ece99a4d75418af07854ada4ab0e0d92c2e245b2d01cd7d612c2ee",
          "sha256": "3fffc1cffe8bc4997c882e1eae764ee1d27471d140baddb8160ec507654adfac",
          "sha1": "4216849b84a2401542c413fb4182f0cd7e2bdf10",
          "md5": "54ae5b978e71a26b0a2a6ee97b9a7e6e"
        }
      ]
    },
    {
      "name": "ProductionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.valentinilk.shimmer",
          "module": "compose-shimmer",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.miui.referrer",
          "module": "homereferrer",
          "version": {
            "requires": "1.0.0.6"
          }
        },
        {
          "group": "com.huawei.hms",
          "module": "componentverifysdk",
          "version": {
            "requires": "13.3.1.301"
          }
        },
        {
          "group": "com.xtech.sdk",
          "module": "xtechcore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.18.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.7.7.aar",
          "url": "xtechads-1.7.7.aar",
          "size": 1686890,
          "sha512": "f8a8d951923a51be0626874550abd3a7de4d79ed16762141b65418b97ee486dd07cf0910e4ece99a4d75418af07854ada4ab0e0d92c2e245b2d01cd7d612c2ee",
          "sha256": "3fffc1cffe8bc4997c882e1eae764ee1d27471d140baddb8160ec507654adfac",
          "sha1": "4216849b84a2401542c413fb4182f0cd7e2bdf10",
          "md5": "54ae5b978e71a26b0a2a6ee97b9a7e6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechads-1.7.7-sources.jar",
          "url": "xtechads-1.7.7-sources.jar",
          "size": 3957,
          "sha512": "1d8e8c9b623839b3f1be386ac766e7bd5131bc4dd5713b277cf4bf9a5ca4fabe66c928e19f50646f78ddb7828e96ca87a1ff720c06d1d619c28dc131075b6673",
          "sha256": "51bf6fd09cd016419173450f8d3e1c84e1ab9ce5b1f568b0c7fb2138b48e4ded",
          "sha1": "bbd5330fb3b5cda74eb52c8d03c0be928594f82d",
          "md5": "c082481d0327a7ab093959679f2faadd"
        }
      ]
    }
  ]
}
