{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.1.2.jar",
          "url": "xtechads-gradle-plugin-1.1.2.jar",
          "size": 14906,
          "sha512": "56b5dbee18c8026805e09714a526ed9553cbad81dc97a026f5fa6806ba5341d6743c93b359ede5c49009e1170477861cc557a2a0a33c6291b95a79e649bc7dde",
          "sha256": "613957bd4226b0fc57487ad5cb307da1d09eebb404849a9aaf6b2910e842c83a",
          "sha1": "055659a17a459ece3e397243374e8e5024bc6eb8",
          "md5": "d36a66da448e3b51ee25df7f6e56af9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.1.2.jar",
          "url": "xtechads-gradle-plugin-1.1.2.jar",
          "size": 14906,
          "sha512": "56b5dbee18c8026805e09714a526ed9553cbad81dc97a026f5fa6806ba5341d6743c93b359ede5c49009e1170477861cc557a2a0a33c6291b95a79e649bc7dde",
          "sha256": "613957bd4226b0fc57487ad5cb307da1d09eebb404849a9aaf6b2910e842c83a",
          "sha1": "055659a17a459ece3e397243374e8e5024bc6eb8",
          "md5": "d36a66da448e3b51ee25df7f6e56af9b"
        }
      ]
    }
  ]
}
