{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechbilling",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.xtech.sdk",
          "module": "xtechcore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechbilling-1.0.2.aar",
          "url": "xtechbilling-1.0.2.aar",
          "size": 88739,
          "sha512": "6d4b18d05d700fbdf2bb240257b79c19bec4ceb3fb58dd568bf16de6d100f3a18fa30791d627d32ee09a9afaee2a6e59b8d2d366038a5b4290a3f6c68a45be04",
          "sha256": "6cca191c4ec1e44e93cd72ee88b00f6fad33fe5e25fc03aa0d49aec02532121e",
          "sha1": "45cac4f2a22497e037a45736f9738cf0c5fbeaf4",
          "md5": "270a6dad55bfb43f7b5dace8b476416a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.xtech.sdk",
          "module": "xtechcore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechbilling-1.0.2.aar",
          "url": "xtechbilling-1.0.2.aar",
          "size": 88739,
          "sha512": "6d4b18d05d700fbdf2bb240257b79c19bec4ceb3fb58dd568bf16de6d100f3a18fa30791d627d32ee09a9afaee2a6e59b8d2d366038a5b4290a3f6c68a45be04",
          "sha256": "6cca191c4ec1e44e93cd72ee88b00f6fad33fe5e25fc03aa0d49aec02532121e",
          "sha1": "45cac4f2a22497e037a45736f9738cf0c5fbeaf4",
          "md5": "270a6dad55bfb43f7b5dace8b476416a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechbilling-1.0.2-sources.jar",
          "url": "xtechbilling-1.0.2-sources.jar",
          "size": 8740,
          "sha512": "70d7eb0cad700834eda94f22f16a5c857551f2369fe12e2e044c6b0d8a95c1ae57ba21fe40d49a6ba3e15b4b8ac0fe37694364935a2ffa807baf84d07a28e2f1",
          "sha256": "a25657d737649be274b458f704130618c02830feb5b8691677cf87b53674ca62",
          "sha1": "74a04378230ca56b92a92553e07353af2a9143ce",
          "md5": "683506322bfd01f43780e9c74789aeb6"
        }
      ]
    }
  ]
}
