{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.9.jar",
          "url": "xtechads-gradle-plugin-1.3.9.jar",
          "size": 14906,
          "sha512": "7c713e5af1921d236f8c70423799a3e18542a05b2513c440fc30e32d5f932e22841737381eda6836f0187b13b95c493e6b6d2aecb1359ef8fae616110ae836e6",
          "sha256": "9b51e06371873adf0e77d7b4f8d2709452c42e59b2f7e9800cabd2fd982b9555",
          "sha1": "b1f0b8449f911b658f30d31f8d263657b8ed6ea3",
          "md5": "a7681f6766d7e72a25e1b785ef7d72d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.9.jar",
          "url": "xtechads-gradle-plugin-1.3.9.jar",
          "size": 14906,
          "sha512": "7c713e5af1921d236f8c70423799a3e18542a05b2513c440fc30e32d5f932e22841737381eda6836f0187b13b95c493e6b6d2aecb1359ef8fae616110ae836e6",
          "sha256": "9b51e06371873adf0e77d7b4f8d2709452c42e59b2f7e9800cabd2fd982b9555",
          "sha1": "b1f0b8449f911b658f30d31f8d263657b8ed6ea3",
          "md5": "a7681f6766d7e72a25e1b785ef7d72d1"
        }
      ]
    }
  ]
}
