{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.0.jar",
          "url": "xtechads-gradle-plugin-1.3.0.jar",
          "size": 14906,
          "sha512": "c168c941f98b0e61c8bd1c2166709de9b82cfb268a36b4cd93ae468f57f351a9eaf35c971b0bf5eec8fa10d25f1f08471adcad249e119c86d05e8830856d05ef",
          "sha256": "86d2f98e92f52155a2e0e905e3fe7c0e6b273f23217cc6f3897c1458d1125dbe",
          "sha1": "1407d1df5506669bbb741ac10534da461de37302",
          "md5": "57f63b36badba8a683598130a55d2f8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.0.jar",
          "url": "xtechads-gradle-plugin-1.3.0.jar",
          "size": 14906,
          "sha512": "c168c941f98b0e61c8bd1c2166709de9b82cfb268a36b4cd93ae468f57f351a9eaf35c971b0bf5eec8fa10d25f1f08471adcad249e119c86d05e8830856d05ef",
          "sha256": "86d2f98e92f52155a2e0e905e3fe7c0e6b273f23217cc6f3897c1458d1125dbe",
          "sha1": "1407d1df5506669bbb741ac10534da461de37302",
          "md5": "57f63b36badba8a683598130a55d2f8f"
        }
      ]
    }
  ]
}
