{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.4.jar",
          "url": "xtechads-gradle-plugin-1.3.4.jar",
          "size": 14906,
          "sha512": "6fa2d035f56f52d069702f7a37b95dffae5c0c9bf19665e4de3032df210e1d99db6a99b214b315862605face0e5f758f39f6e617166791df6982ab176e507470",
          "sha256": "53375f39e6af3780addf117283ea2156efb187edef5644c8654b2ca94e075d68",
          "sha1": "6c80861dd861dd011076c45b2bc2e10ff085e59d",
          "md5": "98412995b435be75c849126bf6441c1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.3.4.jar",
          "url": "xtechads-gradle-plugin-1.3.4.jar",
          "size": 14906,
          "sha512": "6fa2d035f56f52d069702f7a37b95dffae5c0c9bf19665e4de3032df210e1d99db6a99b214b315862605face0e5f758f39f6e617166791df6982ab176e507470",
          "sha256": "53375f39e6af3780addf117283ea2156efb187edef5644c8654b2ca94e075d68",
          "sha1": "6c80861dd861dd011076c45b2bc2e10ff085e59d",
          "md5": "98412995b435be75c849126bf6441c1e"
        }
      ]
    }
  ]
}
