{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.4.jar",
          "url": "xtechads-gradle-plugin-1.5.4.jar",
          "size": 14906,
          "sha512": "3434cfd1478f7e099545a2eeae26de3c3f5eb899dce0728d626a4ad0191cf98d10cf2ccd4555c99621c67139a30a2821fdf1d1ae9029cdd91ecd234dc27d7bd9",
          "sha256": "5f605f661042c1b766e688843830bd5fcaf3105b668663f0bd0a4ccb5b9a41cb",
          "sha1": "95a41f4841b1aad5140d7a502869bf65f439c96c",
          "md5": "7961204e58607e13fb8e516deac675f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.4.jar",
          "url": "xtechads-gradle-plugin-1.5.4.jar",
          "size": 14906,
          "sha512": "3434cfd1478f7e099545a2eeae26de3c3f5eb899dce0728d626a4ad0191cf98d10cf2ccd4555c99621c67139a30a2821fdf1d1ae9029cdd91ecd234dc27d7bd9",
          "sha256": "5f605f661042c1b766e688843830bd5fcaf3105b668663f0bd0a4ccb5b9a41cb",
          "sha1": "95a41f4841b1aad5140d7a502869bf65f439c96c",
          "md5": "7961204e58607e13fb8e516deac675f9"
        }
      ]
    }
  ]
}
