{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.4.jar",
          "url": "xtechads-gradle-plugin-1.5.4.jar",
          "size": 14906,
          "sha512": "fd3a3deaecc98031c943e8a923eb4b182870af60adef54f934a109eaacb1e0d0322e0cca20d52d6807a8cefd076fe031c4b34b47a624c5751c4e82b76657f557",
          "sha256": "7d148a2a994c34183e303ecbc7beb1aa34ffcd0672bf4ec73570d658fc392056",
          "sha1": "1e356f6171dca307fdd78245f986ac6d1f0d6565",
          "md5": "908fa1bd265afb9960c0ab359a102739"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.4.jar",
          "url": "xtechads-gradle-plugin-1.5.4.jar",
          "size": 14906,
          "sha512": "fd3a3deaecc98031c943e8a923eb4b182870af60adef54f934a109eaacb1e0d0322e0cca20d52d6807a8cefd076fe031c4b34b47a624c5751c4e82b76657f557",
          "sha256": "7d148a2a994c34183e303ecbc7beb1aa34ffcd0672bf4ec73570d658fc392056",
          "sha1": "1e356f6171dca307fdd78245f986ac6d1f0d6565",
          "md5": "908fa1bd265afb9960c0ab359a102739"
        }
      ]
    }
  ]
}
