{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.4.jar",
          "url": "xtechads-gradle-plugin-1.5.4.jar",
          "size": 14906,
          "sha512": "e679c697acf796e536890f5bc333310c83a76128dbf17192556a4558461e6450b70a8967c61ccb2ec4ce3bc6d6e9ea3f97a39df7333c90618e307caf8e4093ee",
          "sha256": "d9ec82854d34efca69f09197b55fde751391a3b25c899b5583117f9adff7d490",
          "sha1": "05851e9c2280107166896e3fa5d7c1f544bfb3c2",
          "md5": "f12b1d67764f2aebc2663fa064720d2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.4.jar",
          "url": "xtechads-gradle-plugin-1.5.4.jar",
          "size": 14906,
          "sha512": "e679c697acf796e536890f5bc333310c83a76128dbf17192556a4558461e6450b70a8967c61ccb2ec4ce3bc6d6e9ea3f97a39df7333c90618e307caf8e4093ee",
          "sha256": "d9ec82854d34efca69f09197b55fde751391a3b25c899b5583117f9adff7d490",
          "sha1": "05851e9c2280107166896e3fa5d7c1f544bfb3c2",
          "md5": "f12b1d67764f2aebc2663fa064720d2c"
        }
      ]
    }
  ]
}
