{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.2.jar",
          "url": "xtechads-gradle-plugin-1.5.2.jar",
          "size": 14906,
          "sha512": "40489aa0bf0272d1cf86c7a440844e6f5b68a6267f0c2dad3edff873ae0c93da8e399b41c50088c95ae4d26abae3ae73c0f63a0c1aa4402eb0db16684ada64f4",
          "sha256": "7ba96c6b3c5248a0f960f1fd5a8816673a9e3559c40eb00ddbfcf3fbad444884",
          "sha1": "fbe6abe68d51c6f34fbe3513f8d626370f95530c",
          "md5": "ff6f0023a0af78c82e634c619bf17eb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.5.2.jar",
          "url": "xtechads-gradle-plugin-1.5.2.jar",
          "size": 14906,
          "sha512": "40489aa0bf0272d1cf86c7a440844e6f5b68a6267f0c2dad3edff873ae0c93da8e399b41c50088c95ae4d26abae3ae73c0f63a0c1aa4402eb0db16684ada64f4",
          "sha256": "7ba96c6b3c5248a0f960f1fd5a8816673a9e3559c40eb00ddbfcf3fbad444884",
          "sha1": "fbe6abe68d51c6f34fbe3513f8d626370f95530c",
          "md5": "ff6f0023a0af78c82e634c619bf17eb4"
        }
      ]
    }
  ]
}
