{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.4.7.jar",
          "url": "xtechads-gradle-plugin-1.4.7.jar",
          "size": 14906,
          "sha512": "5f65169e710ef4c1af7593a9f6aefb8242d462e21d9dd048edd614118e5874386fbd111ef3a1b2deaf40b483dd9b6c355f9258cc261c2c2b1d26ca72afc221a8",
          "sha256": "b790e4f245391c31aae54eb21582f6675eb4564e4eac373a89c56013e71dd23a",
          "sha1": "e01333f59621dbc38dcc6e38fcfd759c22210ca8",
          "md5": "ad0ef90df71a81f4e15b08251b97691d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.4.7.jar",
          "url": "xtechads-gradle-plugin-1.4.7.jar",
          "size": 14906,
          "sha512": "5f65169e710ef4c1af7593a9f6aefb8242d462e21d9dd048edd614118e5874386fbd111ef3a1b2deaf40b483dd9b6c355f9258cc261c2c2b1d26ca72afc221a8",
          "sha256": "b790e4f245391c31aae54eb21582f6675eb4564e4eac373a89c56013e71dd23a",
          "sha1": "e01333f59621dbc38dcc6e38fcfd759c22210ca8",
          "md5": "ad0ef90df71a81f4e15b08251b97691d"
        }
      ]
    }
  ]
}
