{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.7.jar",
          "url": "xtechads-gradle-plugin-1.7.7.jar",
          "size": 14906,
          "sha512": "cfcb9de1f2b0477f1328c1dabaa80cf61af4ed7413d5a044cba533a1c8b28ce8c1232286dc6f34346020d42ff06d0f036b5d942a028d8f1504cc8346b0472af4",
          "sha256": "45c1e35307ab5fa10d9574f096c21e443fb7c1efa7e96e3a509f471a8698a054",
          "sha1": "7594c0eb796314ebe0966c48811caa734d2517d6",
          "md5": "e09db3759977d8bcb70aa093b3dc46a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.7.jar",
          "url": "xtechads-gradle-plugin-1.7.7.jar",
          "size": 14906,
          "sha512": "cfcb9de1f2b0477f1328c1dabaa80cf61af4ed7413d5a044cba533a1c8b28ce8c1232286dc6f34346020d42ff06d0f036b5d942a028d8f1504cc8346b0472af4",
          "sha256": "45c1e35307ab5fa10d9574f096c21e443fb7c1efa7e96e3a509f471a8698a054",
          "sha1": "7594c0eb796314ebe0966c48811caa734d2517d6",
          "md5": "e09db3759977d8bcb70aa093b3dc46a7"
        }
      ]
    }
  ]
}
