{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.7.jar",
          "url": "xtechads-gradle-plugin-1.7.7.jar",
          "size": 14906,
          "sha512": "eb8f8ec7de6146bda36d0b5c2cb250aaac3c5f6bd6c1db99b12201e6a21e5faffa43eedb52bafa0271ddfa7caaab831b9beb9413047abe3ec9235b6b29098dd5",
          "sha256": "88d0b200970bcb855ce2aadbcc6ee9e484b0ed85496db7183fb32eeb180c643a",
          "sha1": "5e6f1d7bf5a24026cd630d48ccb0c64373339b9b",
          "md5": "3d6192bbb1ac1ec4c314e5e177fb6f78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.7.jar",
          "url": "xtechads-gradle-plugin-1.7.7.jar",
          "size": 14906,
          "sha512": "eb8f8ec7de6146bda36d0b5c2cb250aaac3c5f6bd6c1db99b12201e6a21e5faffa43eedb52bafa0271ddfa7caaab831b9beb9413047abe3ec9235b6b29098dd5",
          "sha256": "88d0b200970bcb855ce2aadbcc6ee9e484b0ed85496db7183fb32eeb180c643a",
          "sha1": "5e6f1d7bf5a24026cd630d48ccb0c64373339b9b",
          "md5": "3d6192bbb1ac1ec4c314e5e177fb6f78"
        }
      ]
    }
  ]
}
