{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.1.jar",
          "url": "xtechads-gradle-plugin-1.7.1.jar",
          "size": 14906,
          "sha512": "1d137a219bcb9db066a7032ed0c18f488c19143a4346473ff27137f093a2f0d5f5912d379cd304d7cf2e9b49f793731c6428c9b8451f5dfdb85abfbb21b4bb6c",
          "sha256": "712c54d25f5c901bd236badfe3eb41fc24fe91066bbea733ded917a4517fbd1b",
          "sha1": "250358bd36fa22fdecf2dc98d0ed8a6c7f67b58e",
          "md5": "244888fa1246ba5bb98fbf9c64e865cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.1.jar",
          "url": "xtechads-gradle-plugin-1.7.1.jar",
          "size": 14906,
          "sha512": "1d137a219bcb9db066a7032ed0c18f488c19143a4346473ff27137f093a2f0d5f5912d379cd304d7cf2e9b49f793731c6428c9b8451f5dfdb85abfbb21b4bb6c",
          "sha256": "712c54d25f5c901bd236badfe3eb41fc24fe91066bbea733ded917a4517fbd1b",
          "sha1": "250358bd36fa22fdecf2dc98d0ed8a6c7f67b58e",
          "md5": "244888fa1246ba5bb98fbf9c64e865cb"
        }
      ]
    }
  ]
}
