{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.1.jar",
          "url": "xtechads-gradle-plugin-1.7.1.jar",
          "size": 14906,
          "sha512": "1d2aa795071d9e0f0c33258ad42850df7b3791dd69d674ebe874fd95c811931a83faa6c24cd866345c14c3cbf018c9b6fff8b639111b75b21c286487f5f3cd89",
          "sha256": "33611eb2c860c6170ee4c82bd79c91c3d0c31417146b797989e1f047d09061e1",
          "sha1": "11c07b7036966759057c7dc726baffac43b1c984",
          "md5": "9f7cdb965b546b81521a9804743e4ef9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.1.jar",
          "url": "xtechads-gradle-plugin-1.7.1.jar",
          "size": 14906,
          "sha512": "1d2aa795071d9e0f0c33258ad42850df7b3791dd69d674ebe874fd95c811931a83faa6c24cd866345c14c3cbf018c9b6fff8b639111b75b21c286487f5f3cd89",
          "sha256": "33611eb2c860c6170ee4c82bd79c91c3d0c31417146b797989e1f047d09061e1",
          "sha1": "11c07b7036966759057c7dc726baffac43b1c984",
          "md5": "9f7cdb965b546b81521a9804743e4ef9"
        }
      ]
    }
  ]
}
