{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.6.2.jar",
          "url": "xtechads-gradle-plugin-1.6.2.jar",
          "size": 14906,
          "sha512": "e397b3ed36be82e6451bea24b816477779dd20334d0369075b1eac9493775a4601e64810ed6203e40cdfb3bb043683b60951461dcbf7d35815461da088683894",
          "sha256": "6f3ece7874dec7084f744564e7675283c161a19016e4de4644c785dd907b3de0",
          "sha1": "831b185df72c9dcdcfff115de9d1f64ac5b4a15d",
          "md5": "52d6167e3ec6a645786199a42aea6518"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.6.2.jar",
          "url": "xtechads-gradle-plugin-1.6.2.jar",
          "size": 14906,
          "sha512": "e397b3ed36be82e6451bea24b816477779dd20334d0369075b1eac9493775a4601e64810ed6203e40cdfb3bb043683b60951461dcbf7d35815461da088683894",
          "sha256": "6f3ece7874dec7084f744564e7675283c161a19016e4de4644c785dd907b3de0",
          "sha1": "831b185df72c9dcdcfff115de9d1f64ac5b4a15d",
          "md5": "52d6167e3ec6a645786199a42aea6518"
        }
      ]
    }
  ]
}
