{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.0.8.jar",
          "url": "xtechads-gradle-plugin-1.0.8.jar",
          "size": 14906,
          "sha512": "846ea50c25040e9a48776db204e6b324bacc4d045a094aeaee43037af910cd91dd27046412b9718047993ebb60f43e537a8fa1f3fb01bd2bead2f036a6dc3473",
          "sha256": "a2d2af21b9385de4d20408db687d9bfbe7ca8c0fafc51adcd7f67be2b2422073",
          "sha1": "b839ba74f5d91a3b53f190c4d05190e1439b78bb",
          "md5": "54c38681048a116beae2bbf6ba6716bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.0.8.jar",
          "url": "xtechads-gradle-plugin-1.0.8.jar",
          "size": 14906,
          "sha512": "846ea50c25040e9a48776db204e6b324bacc4d045a094aeaee43037af910cd91dd27046412b9718047993ebb60f43e537a8fa1f3fb01bd2bead2f036a6dc3473",
          "sha256": "a2d2af21b9385de4d20408db687d9bfbe7ca8c0fafc51adcd7f67be2b2422073",
          "sha1": "b839ba74f5d91a3b53f190c4d05190e1439b78bb",
          "md5": "54c38681048a116beae2bbf6ba6716bf"
        }
      ]
    }
  ]
}
