{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.0.8.jar",
          "url": "xtechads-gradle-plugin-1.0.8.jar",
          "size": 14906,
          "sha512": "778b78a8a8ad61b76531cfdcde99ef065f1ddacda181d500cf28dd51e982de731a1560f57d45fe3c2304139786d7e28fd3be893836a85ac65383f5a57e98b01e",
          "sha256": "d1049863e16b0426e66821feb96a80fb4e1004871a5ebc168540ee354891ca66",
          "sha1": "017485e8e294fd2ff38d8bf3ca43a55455441a1f",
          "md5": "547f6569bfdf454ceb70142a12a5e2b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.0.8.jar",
          "url": "xtechads-gradle-plugin-1.0.8.jar",
          "size": 14906,
          "sha512": "778b78a8a8ad61b76531cfdcde99ef065f1ddacda181d500cf28dd51e982de731a1560f57d45fe3c2304139786d7e28fd3be893836a85ac65383f5a57e98b01e",
          "sha256": "d1049863e16b0426e66821feb96a80fb4e1004871a5ebc168540ee354891ca66",
          "sha1": "017485e8e294fd2ff38d8bf3ca43a55455441a1f",
          "md5": "547f6569bfdf454ceb70142a12a5e2b7"
        }
      ]
    }
  ]
}
