{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.5.jar",
          "url": "xtechads-gradle-plugin-1.7.5.jar",
          "size": 14906,
          "sha512": "928a1b08eb69f1587d054e94058f2d087aa5ff6f2740068102a03ce2810495ab2317c153557b7042fd4cc8fbddfdedc6d8d805b41a5dce327c9c069263960fc1",
          "sha256": "4aa3de32509377fefdbd3ad554d7d3b923c2489c5aa832371c5cdbb43781b722",
          "sha1": "fdcb877d2a6540bc69673a24aaa2f3d4e42addc5",
          "md5": "56e3c1b75a6a135ffb0458aeaac61029"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.7.5.jar",
          "url": "xtechads-gradle-plugin-1.7.5.jar",
          "size": 14906,
          "sha512": "928a1b08eb69f1587d054e94058f2d087aa5ff6f2740068102a03ce2810495ab2317c153557b7042fd4cc8fbddfdedc6d8d805b41a5dce327c9c069263960fc1",
          "sha256": "4aa3de32509377fefdbd3ad554d7d3b923c2489c5aa832371c5cdbb43781b722",
          "sha1": "fdcb877d2a6540bc69673a24aaa2f3d4e42addc5",
          "md5": "56e3c1b75a6a135ffb0458aeaac61029"
        }
      ]
    }
  ]
}
