{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "ProductionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.adjust.sdk",
          "module": "adjust-android",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.3.1.aar",
          "url": "xtechads-1.3.1.aar",
          "size": 1653846,
          "sha512": "bfd50ca98743a1370b2c160b9064631d1d9ba2bf8c1db57446fbef114fde93a63cb9640ab5d0b932403799b19a101ec4421c51638d7ae7bc285e89e87462fdd8",
          "sha256": "5259f30c3f046d6ee284a542f19c1cb5b3fcc15a27c001dcaab4524ceef0687d",
          "sha1": "d95e1fe1cf82dbae1a51aa16767c3d246cb5eaf8",
          "md5": "3c1ffe99c148326a396a45b66f0dd1f6"
        }
      ]
    },
    {
      "name": "ProductionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.valentinilk.shimmer",
          "module": "compose-shimmer",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.adjust.signature",
          "module": "adjust-android-signature",
          "version": {
            "requires": "3.67.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.adjust.sdk",
          "module": "adjust-android",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.3.1.aar",
          "url": "xtechads-1.3.1.aar",
          "size": 1653846,
          "sha512": "bfd50ca98743a1370b2c160b9064631d1d9ba2bf8c1db57446fbef114fde93a63cb9640ab5d0b932403799b19a101ec4421c51638d7ae7bc285e89e87462fdd8",
          "sha256": "5259f30c3f046d6ee284a542f19c1cb5b3fcc15a27c001dcaab4524ceef0687d",
          "sha1": "d95e1fe1cf82dbae1a51aa16767c3d246cb5eaf8",
          "md5": "3c1ffe99c148326a396a45b66f0dd1f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechads-1.3.1-sources.jar",
          "url": "xtechads-1.3.1-sources.jar",
          "size": 3761,
          "sha512": "02817f15c5bcd3a83e1be4a9a8b55065de293a72d68eb783399aa6b6d2c389f71bcd5baec4eff265979b914cc54cb0120560e52c7e9998f1957a8d563b8a9fee",
          "sha256": "18798f4eefc7dc0818dfc908399b267798d5f385aad2004ed689c1d9509aa474",
          "sha1": "fc135a0a1662abf322f2e2aafb6b015eb82477f6",
          "md5": "3dfc27efaef8d3080051624f4a4449ea"
        }
      ]
    }
  ]
}
