{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "ProductionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.18.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.7.0.aar",
          "url": "xtechads-1.7.0.aar",
          "size": 1699506,
          "sha512": "188be8e83e7bf8216069319edd44f0d5c1263f86e547eed1f89c7e971a7d751f63c2e64360b7a27e18715dd3a4de80ff3265643e31351d78fd6bc3ed342e7a6f",
          "sha256": "710398d17bcf0e6811640de0674d118a02c41904f1360eb1f637c5efe304a91a",
          "sha1": "c6accb0ecd4351ffd79ddb64422bbf3dfee57347",
          "md5": "e4f6f4755e0003aa0e6c70c3707eb09d"
        }
      ]
    },
    {
      "name": "ProductionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.valentinilk.shimmer",
          "module": "compose-shimmer",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.miui.referrer",
          "module": "homereferrer",
          "version": {
            "requires": "1.0.0.6"
          }
        },
        {
          "group": "com.huawei.hms",
          "module": "componentverifysdk",
          "version": {
            "requires": "13.3.1.301"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-measurement-api"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.21.0.4"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.18.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "xtechads-1.7.0.aar",
          "url": "xtechads-1.7.0.aar",
          "size": 1699506,
          "sha512": "188be8e83e7bf8216069319edd44f0d5c1263f86e547eed1f89c7e971a7d751f63c2e64360b7a27e18715dd3a4de80ff3265643e31351d78fd6bc3ed342e7a6f",
          "sha256": "710398d17bcf0e6811640de0674d118a02c41904f1360eb1f637c5efe304a91a",
          "sha1": "c6accb0ecd4351ffd79ddb64422bbf3dfee57347",
          "md5": "e4f6f4755e0003aa0e6c70c3707eb09d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xtechads-1.7.0-sources.jar",
          "url": "xtechads-1.7.0-sources.jar",
          "size": 3957,
          "sha512": "0c145639f02a5dd8a574b3684781fa29140de7f7fb9f969442890e5f0ed41b8c19836eaed62981a1885d9aaa6bd33e295a78120288c01faf1eafacf1fb0d6a51",
          "sha256": "b03af6848838bee1e3f898c4fdffc7ebb735cbd92228495f4f5a9e44214bedf4",
          "sha1": "4a3ed65670a2b9d4dd07d82435536000686341ae",
          "md5": "e9d9b3968494c3ae5341f1d178197ed1"
        }
      ]
    }
  ]
}
