{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtech.sdk",
    "module": "xtechads-gradle-plugin",
    "version": "1.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.8.7.jar",
          "url": "xtechads-gradle-plugin-1.8.7.jar",
          "size": 14906,
          "sha512": "e3aff60eab2b3ab1fb80ecaa7d4d22c3e7723468b400dcea26a0f158e10d357b2e7a4a3ba00c706b414aec1e9be6fb953c6a9b5689beabcaef0c468af2138d77",
          "sha256": "2ad6025b3d343921e1ca47443da9b4f3ae60a761a60472b35770db16f018f7f8",
          "sha1": "d658e026606c3aa81a92cd664534743f3567c1d5",
          "md5": "875542dbfa6277b161be19345fb04be4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xtechads-gradle-plugin-1.8.7.jar",
          "url": "xtechads-gradle-plugin-1.8.7.jar",
          "size": 14906,
          "sha512": "e3aff60eab2b3ab1fb80ecaa7d4d22c3e7723468b400dcea26a0f158e10d357b2e7a4a3ba00c706b414aec1e9be6fb953c6a9b5689beabcaef0c468af2138d77",
          "sha256": "2ad6025b3d343921e1ca47443da9b4f3ae60a761a60472b35770db16f018f7f8",
          "sha1": "d658e026606c3aa81a92cd664534743f3567c1d5",
          "md5": "875542dbfa6277b161be19345fb04be4"
        }
      ]
    }
  ]
}
